name: chart_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  csv: ^5.1.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  get: ^4.6.6
  # Replacing screenshot package with alternatives
  image_gallery_saver: ^2.0.3
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Adding dependency overrides to fix the file_picker platform implementation issues
dependency_overrides:
  file_picker:
    git:
      url: https://github.com/miguelpruivo/flutter_file_picker.git
      ref: master  # Using the latest version from the master branch

flutter:
  uses-material-design: true
  
  assets:
    - assets/
