name: chart_generator
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  csv: ^5.1.1
  fl_chart: ^0.66.0
  intl: ^0.19.0
  get: ^4.6.6
  screenshot: ^2.1.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
